# nginx-app.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd 
spec:
  project: default
  source:
    # ----------------------------------------------------------------------
    # ⬇️ ⬇️ CRITICAL: CHANGE THIS TO YOUR ACTUAL GIT REPO URL ⬇️ ⬇️
    # ----------------------------------------------------------------------
    repoURL: https://github.com/YOUR_USERNAME/devops-eks-assignment.git 
    targetRevision: HEAD
    path: manifests # Points to the folder containing your YAMLs
  destination:
    server: https://kubernetes.default.svc
    namespace: default 
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
